### PR TITLE
Added static files required for swagger-ui to work

### LINKED ISSUE #210: Swagger static files are 404 in the RTD documentation page
see: https://django-formidable.readthedocs.io/en/latest/api.html

all the "_static" files are missing.

### PR DESCRIPTION
**Pull request by brunobord**
## Review

This PR closes #210

* [x] Docs/comments - maybe add a how-to in the readme to explain how to update/upgrade the swagger static files
* [x] `CHANGELOG.rst` Updated
* [ ] Delete your branch

### CODE REVIEW

**Comment by brunobord** [comment]
The problem: when building the docs, RTD is running  ``sphinx-build -b html . _build/html`` ; and thus, skipping the "make collectstatic" bit that was supposed to solve the pb.
It'd mean that we must tell sphinx where are the static files, and thus committing them in the repository. Sadly.

(or if you have a genius idea, I'll take it)

**Comment by mgu** [comment]
we could use swagger-ui from a CDN ?
https://cdnjs.com/libraries/swagger-ui

**Comment by brunobord** [comment]
mmmm... good idea, indeed. *and* we wouldn't have to upgrade them, but just point at the *latest*? I'll try this out tomorrow.

**Comment by brunobord** [comment]
using the cdn didn't work at all, and you still need the "collecstatic" bit to be executed before building the doc with sphinx, otherwise your `formidable.js` won't be up-to-date.

So the doc workflow is described in the dev doc.

**Pull request merged**
